iRayanKhan/homebridge-tuya

- .gitignore
- README.md
- index.js
- lib/dimmer.js
- lib/discovery.js
- package.json
Added optional ability to use a tuya based dimmer switch, not a color bulb, just the dimmer. Tested with six simultaneous [MJ-SD01](https://smile.amazon.com/gp/product/B07FXYSVR1) controlling LED lights via Homebridge on HomePod, Apple Watch, and iPhone. Works as expected with scenes and triggers.
> Adds Support for Basic Dimmer Switch

- lib/dimmer.js
This HAP Get Event handler is redundant when using events and updateValue.  And actually slows down the time it takes the Home app to open.  ( In my setup it adds 5 seconds to the Home App startup time.)
Max, this got missed/dropped in the original Pull request for events.  And I just found this when I was looking into why my Home app was so slow to start up.
> Redundant get Request

- index.js
- lib/AirPurifierAccessory.js
Addition of a new AirPurifier device type. Also includes an optional setting to include Air Quality sensor details. The new `AirPurifierAccessory.js` file contains a lot of this detail as comments, and enhancements that could be made. 
Settings supported:
* noRotationSpeed - boolean which, if set to true, will disable the fan speed control
* fanSpeedSteps - The number of fan speed stops that the device supports. The default is 100.
* showAirQuality - boolean for enabling the air quality service. The default is false, which will not include air quality values. 
* nameAirQuality - Allows customisation of the air quality sensor name. Default is 'Air Quality'
* noChildLock - boolean for disabling the child lock feature. The default is false, which will enable the child lock feature
This …
> Addition of AirPurifierAccessory

- index.js
- lib/DehumidifierAccessory.js
Default values are taken from Rohnson R-9420 - can by overwritten in config. Only basic settings supported for now (temperature & humidity sensors, low/high fan speed, child lock & target humidity level).
> Initial commit of DehumidifierAccessory

- lib/AirPurifierAccessory.js
I've added support for the Breville Smart Air Connect air purifier (and presumably others in the same range). It has some quicks, including expecting commands as text labels rather than integers. I've changed _rotationStops to a dict to lookup the correct command for each percent power setting and hard-coded some of the other labels in. I've also moved the text `Air Quality` characteristic to DP22, which is where it shows up on the Breville. 
I have tested this on the Breville, but I don't have any others to test, so there may be some breaking changes here, sorry.
> initial support for breville smart connect air purifier

- lib/TuyaAccessory.js
To prevent a fast ECONNRESET loop when turning off an accessory and turning it back on more than a few minutes later, e.g. to move and re-purpose it, did the following: In _socket.on('error') recorded the _connect() Timeout in this._socket._errorReconnect and tested that value before setting another Timeout to prevent scheduling two _connect() calls; Added _errorReconnect to the list of Timeouts cleared in _connect(); In this._socket.reconnect, incremented the Attempt Counter this._connectionAttempts just before the call to this._socket.connect(). The attempt counter was being incremented only on _connect(), not on reconnect; In _socket.on('connect'), cleared an existing pinger Timeout before setting another one; Added several DEBUG console.log statements to help trace what was happening …
> Prevent an ECONNRESET storm when accessories turn off

- index.js
Update the cachedAccessories displayName when it differs from the name in the configuration. This allows you to re-purpose an accessory while eliminating potentially confusing log messages that show different names.
> Sync the cachedAccessories displayName with the configuration

- lib/GarageDoorAccessory.js
Legacy code was not updated with latest parameter name
Change https://github.com/iRayanKhan/homebridge-tuya/commit/82c6063693f57032bbbf8fbf53fc4741fff6307d#diff-62ef107d13ba44e1952ec6ddf70355ce5f42a30e42a94ed009155ad26881a24aL88
> Fix crash on launch for garage accessory with ReferenceError: dps is not defined

- lib/GarageDoorAccessory.js
Wofea uses `dp 101` to indicate door status.
**Examples**
Closed
```{"1":false,"7":0,"101":false}```
Open
```{"1":true,"7":0,"101":true}```
Note `dp 1` is still used for state changes.
> Added dpStatus configuration for Wofea garage door

- config.schema.json
- lib/SimpleHeaterAccessory.js
Reverts iRayanKhan/homebridge-tuya#251
> Revert "split factor variable for heater temperatures"

- lib/SimpleBlindsAccessory.js
- Manufacturer types possible (case-insensitive): "**type1**" (_simpleBlinds_) & "**type2**" (_simpleBlinds2_)
- By default the device defaults to type1 if it's not specified.
> Combined SimpleBlinds and SimpleBlinds2

- lib/BaseAccessory.js
Updated the function that issues a setState for devices; this will ensure values already true in the device dps is not sent again in another command. While this will still send separate commands it will eliminate continously getting a light to turn ON while changing brightness in accordance with Issue #252 - this issue is now closed.
> Updated setMultiState Function

- lib/RGBTWLightAccessory.js
- Removed 
// Avoid cross-mode complications due rapid commands
this.device.state[this.dpMode] = this.cmdWhite;
> Removed RapidCommand Safety Net

- .gitignore
- index.js
When adding a new Device and leaving the "Manufacturer" field blank (Which is a non-required field) we get the following error:
```
[TuyaDiscovery] Failed to parse discovery response on port 6667: {}
```
The exception:
```
TypeError: Cannot read property 'trim' of undefined
at TuyaLan.addAccessory (/homebridge/node_modules/homebridge-tuya/index.js:215:93)
at TuyaDiscovery.<anonymous> (/homebridge/node_modules/homebridge-tuya/index.js:129:22)
at TuyaDiscovery.emit (events.js:315:20)
at TuyaDiscovery._onDiscover (/homebridge/node_modules/homebridge-tuya/lib/TuyaDiscovery.js:156:14)
at TuyaDiscovery._onDgramMessage (/homebridge/node_modules/homebridge-tuya/lib/TuyaDiscovery.js:135:58)
at Socket.emit (events.js:315:20)
at UDP.onMessage (dgram.js:919:8)
```
The old .trim() on line 212 is not …
> Fix empty manufacturer error

- index.js
Allows for plugin to work with empty configuration file for tester and first time users.
> Allow Empty Config

- lib/SimpleFanAccessory.js
- lib/SimpleFanLightAccessory.js
Removing the standalone setActive function that turns the fan on and instead sing the SetMultiState function to turn the fan on when it sets the speed.
Some Fan Controllers like the DETA 3 Speed Fan Controller with Light default to a particular speed when it is turned on. The existing logic sets the fan to active and then sets the speed. This causes a clash as the response from the switch turning the fan on will sets the speed to 3 and override the subsequent update speed call. This change fixes that by ensuring that only one call is made to turn the fan on and set the rotation speed.
> Updating FanController logic to merge the setSpeed and SetActive functions

- bin/cli-decode.js
- index.js
<s>Allow latin alphanumeric **and special character** for local_key</s>
Remove local_key check
Fixes #409 
Fixes #410
> Allow new format for local_key

- index.js
- lib/BaseAccessory.js
- lib/GarageDoorAccessory.js
- lib/MultiOutletAccessory.js
- lib/RGBTWLightAccessory.js
- lib/SimpleBlindsAccessory.js
- lib/SimpleFanAccessory.js
- lib/SimpleFanLightAccessory.js
- lib/SimpleHeaterAccessory.js
- lib/SimpleLightAccessory.js
- lib/SwitchAccessory.js
- lib/TuyaAccessory.js
- lib/TuyaDiscovery.js
- lib/ValveAccessory.js
Most logs use `console.log` instead of the Logging object of Homebridge. I fixed it.
> Unify logs

- config.schema.json
- index.js
`SimpleBlinds2` no longer exists as an accessory type since this commit https://github.com/iRayanKhan/homebridge-tuya/commit/f85c4e3d9a1c3c138162daed68f86b5c03c8d835
> Remove SimpleBlinds2 from config.schema.json and index.js

- lib/BaseAccessory.js
- lib/SimpleFanAccessory.js
- lib/SimpleFanLightAccessory.js
This allows Siri calls to "set fan to high/medium/low" for 100%/67%/33% where it would previously report 3%/2%/1% and asking for low would try 33% and give high.
> Shift SimpleFan and SimpleFanLight to report %

- lib/SimpleFanAccessory.js
- lib/SimpleFanLightAccessory.js
Not sure exactly what makes this environmentally dependent, but my fan controllers don't speak string.
It's not the most elegant solution, so I'm open to alternatives. But it does work, and defaults to using .toString() if that's the more commonly used form.
> Add useStrings config setting to make .toString() conversion optional
